version: '3.2'

services:
  influxdb:
    image: influxdb:2.3.0
    volumes:
      - influx:/root/.influxdb2
    networks:
      - routing
      - network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    env_file: ../../.env

networks:
  network:
    driver: overlay
    attachable: true
  routing:
    external: true

volumes:
  influx:
