version: "3.9"
services:
  registry:
    image: registry:2
    deploy:
      replicas: 1
      placement:
        constraints: [ node.role == manager ]
    ports:
      - "5000:5000"
    volumes:
      - /root/registry:/registry
    environment:
      - "REGISTRY_AUTH=htpasswd"
      - "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm"
      - "REGISTRY_AUTH_HTPASSWD_PATH=/registry/htpassword"
    networks:
      - routing

networks:
  routing:
    external: true