version: "3.9"
services:
  env-proxy:
    image: nginx:latest
    deploy:
      replicas: 1
      placement:
        constraints: [ node.role == manager ]
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    networks:
      - routing
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./env-proxy/nginx.conf:/etc/nginx/conf.d/default.conf

networks:
  routing:
    external: true
