version: '3.2'

services:
  cadvisor:
    image: google/cadvisor:v0.33.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    networks:
      - cadvisor_network
    deploy:
      mode: global

  influx:
    image: influxdb:2.3.0
    volumes:
      - influx:/var/lib/influxdb
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

networks:
  cadvisor_network:
    driver: overlay
    attachable: true

volumes:
  portainer_data:
